### ISSUE TITLE
type of key

### ISSUE THREAD

**Issue by tchereau** [elseif/MikroTikPatch#3]
In your pipeline, there is some env using private/public key
```yml
      LATEST_VERSION_URL: 'https://upgrade.mikrotik.com/routeros/NEWESTa7.stable'
      LATEST_VERSION: "7.15"
      CUSTOM_LICENSE_PRIVATE_KEY: ${{ secrets.CUSTOM_LICENSE_PRIVATE_KEY }}
      CUSTOM_LICENSE_PUBLIC_KEY: ${{ secrets.CUSTOM_LICENSE_PUBLIC_KEY }}
      CUSTOM_NPK_SIGN_PRIVATE_KEY: ${{ secrets.CUSTOM_NPK_SIGN_PRIVATE_KEY }}
      CUSTOM_NPK_SIGN_PUBLIC_KEY: ${{ secrets.CUSTOM_NPK_SIGN_PUBLIC_KEY }}
      MIKRO_LICENSE_PUBLIC_KEY: ${{ secrets.MIKRO_LICENSE_PUBLIC_KEY }}
      MIKRO_NPK_SIGN_PUBLIC_LKEY: ${{ secrets.MIKRO_NPK_SIGN_PUBLIC_LKEY }}
```

what kind of key is it ? 
As I saw you used ``toyecc`` I guess it could be
- ECDSA
- ECIES
- ECDH
- Elgamal
- Ed25519
- Curve25519

the question is which one ?

ty for your work :)
